### ISSUE TITLE
limit and offset_minutes aren't optional

### ISSUE THREAD

**Issue by dlarrick** [dhanani94/mbta-card#3]
Thanks for this! One comment: 'limit' and 'offset_minutes' aren't optional. If they're not set in the YAML, nothing gets displayed.

**Comment by MikeFez** [comment]
Ah, thanks for pointing this out! I'm actually going to close down this fork and work within the original repository

**Comment by MikeFez** [comment]
Long overdue but this has been resolved in the readme by stating that those values are required., thank you for pointing this out.
