### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by InterferencePattern** [dhanani94/mbta-card#6]
Would you mind clarifying the instructions in the README? Certain parts are unclear, such as this one:

```
Link mbta-card inside you .
```
and
```
offsets the minimum minutes remaining before arrival
```

**Comment by ScottG489** [comment]
I was also confused by the second one and think the docs can be improved.

It's similar to `limit` in that it restricts what predictions show up. So `limit` will make it so not more than `n` predictions are shown and `offset_minutes` will make it so no predictions with a value less than `n` minutes show up. For instance, you probably don't care if a train is arriving at your desired station in 3 minutes if you're a 15 minute walk away.

**Comment by InterferencePattern** [comment]
Thanks @ScottG489!

**Comment by InterferencePattern** [comment]
#7
